---

- hosts: nginx
  tasks:
  - name: Install nginx repo
    yum_repository:
        name: nginx
        description: nginx repository
        baseurl: http://nginx.org/packages/mainline/centos/7/$basearch/
        gpgcheck: no
        enabled: yes

  - name: Install nginx
    yum:
        name: nginx
        state: latest

  - name: Allow http
    iptables:
        action: insert
        chain: INPUT
        protocol: tcp
        destination_port: 80
        jump: ACCEPT
        rule_num: 1
        
    notify:
        - nginx_res

  handlers:
        - name: nginx_res
          service:
             name: nginx
             state: restarted
             enabled: yes
