---

- hosts: vms
  tasks:
  - name: Install apache server
    yum:
        name: httpd
        state: latest
    notify:
        - service enable

  handlers:
        - name: service enable
          service:
                name: httpd
                state: restarted
                enabled: yes

